### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by henniska** [mikkokotola/Marjapaikat#1]
21.09.2017 21:12:50 Download

- Projekti-idea on omalaatuinen ja mielekäs.
- Huomasin, että tällä hetkellä marja-näkymä ei toimi. Tämä pitäisi korjata. 
- Dokumentaatiossa on ristiriitaista tietoa. Käsitekaavio ja relaatiotietokantakaavio eivät täsmää. Liitostaulut Marjakäynti ja Marjastajamarja on muutettu Marjasaaliiseen ja Suosikkimarjaan. Dokumentaatio pitäisi siis päivittää.
- Marjan erottaminen käyttäjästä ei minun mielestä vaikuta toimivalta. Kukin käyttäjä voi vaikuttaa muiden käyttäjien marjavalikoimaan (lisäämällä ja poistamalla). Parempi käytäntö olisi yhdistää marja suoraan käyttäjään (monesta moneen), nyt jokaisella käyttäjällä olisi yksityinen marjakokokoelma. Toinen vaihtoehto olisi antaa marjanlisäys ja -poisto oikeuden vain ylläpitäjälle.
- Vaikka Kaynti toimii tällä hetkellä hyvin, se voisi olla mielekästä yhdistää se suoraan käyttäjään.
- Tietokannassa on monia attribuutteja joihin voisi laittaa 'NOT NULL'. Esimerkiksi taulussa Marjasaalis 'maara' attribuutti ja taulussa Marja 'nimi' attribuutti.
- Muuten koodi näyttää mielestäni hyvältä.

**Comment by mikkokotola** [comment]
Kiitos kommenteista!

- Marja-näkymä oli tosiaan rikki to-pe. Korjasin sen nyt.
- Dokumentaatiosta oli varmaan vielä käyntihetkelläsi vanha versio. Mainitsemasi kahden taulun nimet muuttuivat viikon 3 aikana.
- Mietin tuota Marjan ja Marjastajan suhdetta kommenttisi perusteella. Sovelluksen kannalta kaikkien käyttäjien "yhteisten" marjojen olemassaolo on keskeistä, koska sovelluksessa ylläpidetään poimintamääriä per marja ja "Top-poimijat"-listoja. Peruskäyttäjät voivat vain lisätä, eivät poistaa, marjoja (vain ylläpitäjä voi poistaa ja myös yhdistää duplikaatteja).
- NOT NULLien lisääminen on hyvä idea - katson nuo kommentoimasi läpi.
